#!/usr/bin/perl

@profiles = qw{$ENV{HOME}/.bash_profile $ENV{HOME}/.bash_login $ENV{HOME}/.profile};

$p = "";
foreach (@profiles) {
    if (-e $_ && $p eq "") {
	$p = $_;
    };
};
$p = $profiles[0] if $p eq "";

if (!-e "$p") {
    print "$p does not exist - creating!\n";
};

print "Adding bushcraft path to $p\n";
open F,">>$p";
print F "# If you want to remove bushcraft DELETE FROM HERE ...\n";
if ($ARGV[0] eq "") {
    print F "PATH=\"".
	"\$HOME/bushcraft/bin:".
	"\$HOME/bushcraft/bin_connect_to_headless_pi:".
	"\$PATH\"\n";
};
if ($ARGV[0] eq "pi") {
    print F "PATH=\"".
	"\$HOME/bushcraft/bin:".
	"\$HOME/bushcraft/bin_pi:".
	"\$HOME/bushcraft/bin_pi_autorun:".
	"\$PATH\"\n";
};
print F "# ... DELETE TO HERE.\n\n";
close F;
# system "source '$p'";
