#!/usr/bin/perl

if (-e "/boot/bootcode.bin") {
   chdir();
   chdir("bushcraft/init");
   foreach (qw{initreq
write-sysinfo-init-autostart
first-start-init-autostart
cron-init
vnc-init-autostart
vnc-init-password}) {
       print "\n\n******** $_ *********\n\n";
       system "$_";
   };
   print "\n\n******** add-path-to-profile pi  *********\n\n";
   system "add-path-to-profile pi";
   print "
If you want email to work, please run
      email-init
";

} else {
    print "
This script is meant for running on Raspberry Pi only.
Exiting.
";
};


