#!/usr/bin/perl

if (-e "/boot/bootcode.bin") {
   chdir();
   chdir("bushcraft/init");
   if ($ARGV[0] eq "-i") {
       print "*** CONFIG FOR $ARGV[1] ***\n";
       system("$ENV{HOME}/bushcraft/bin/bushcraft-config '$ARGV[1]'");	           
   };

@package = ("add-path-to-profile pi",
"initreq",
"write-sysinfo-init-autostart",
"firststart-init-autostart",
"cron-init",
"vnc-init-autostart",
"vnc-init-password",
"email-init --force");
   foreach (@package) {
       if ($ARGV[0] eq "" || $ARGV[0] eq "-i") {
	   print "\n\n******** $_ *********\n\n";
	   system "./$_";
       } else {
	   print "\n\n******** $_ *********\n\n";
	   print "To install '$_' type y and press ENTER\n";
	   ($ans = <STDIN>) =~ s/\s//g;
	   if ($ans eq "y") {
	       system "./$_";
	       print "\nInstalled!\n\n";
	   } else {
	       print "Not installed.\n\n";
	   };
       };
   };

   print "To get bushcraft fully working, now type

. .profile

and press enter. If you get 'file not found', type:

cd; . .profile

Alternatively, close the terminal, and log in again.

";

} else {
    print "
This script is meant for running on Raspberry Pi only.
Exiting.
";
};


