#!/usr/bin/perl

if (-e "/boot/bootcode.bin") {
   chdir();
   chdir("bushcraft/init");
@package = ("add-path-to-profile pi",
"initreq",
"write-sysinfo-init-autostart",
"first-start-init-autostart",
"cron-init",
"vnc-init-autostart",
"vnc-init-password",
"email-init");
   foreach (@package) {
       if ($ARGV[0] eq "") {
	   print "\n\n******** $_ *********\n\n";
	   system "$_";
       } else {
	   print "\n\n******** $_ *********\n\n";
	   print "To install '$_' type y and press ENTER\n";
	   ($ans = <STDIN>) =~ s/\s//g;
	   if ($ans eq "y") {
	       system "./$_";
	       print "\nInstalled!\n\n";
	   } else {
	       print "Not installed.\n\n";
	   };
       };
   };

} else {
    print "
This script is meant for running on Raspberry Pi only.
Exiting.
";
};


