#!/usr/bin/perl

$sudo = "";
if ($ARGV[0] eq "off" || $ARGV[0] eq "--off") {
    system "$sudo crontab -l > /tmp/crontmp";
    system "cat /tmp/crontmp | grep -v '#Bushcraft' | grep -v '/home/pi/bushcraft/bin_pi_autorun/cron_commands' > /tmp/crontmp2";
    system "$sudo crontab /tmp/crontmp2; rm /tmp/crontmp; rm /tmp/crontmp2";
} else {
    system "$sudo crontab -l > /tmp/crontmp";
    open F,">>/tmp/crontmp";
    print F "\n#Bushcraft starts\n*/10 * * * * /home/pi/bushcraft/bin_pi_autorun/cron_commands\n#Bushcraft ends\n";
    close F;
    system "$sudo crontab /tmp/crontmp; rm /tmp/crontmp";
};
print "*** CURRENT CRONTAB ***\n";
print "*** FOR ROOT ***\n" if $sudo ne "";
system "$sudo crontab -l";
print "*** *** ***\n";
