#!/usr/bin/perl
# See 
# http://iqjar.com/jar/sending-emails-from-the-raspberry-pi/
# for details.

$ldir = "$ENV{HOME}/.config/bushcraft/";

$lconf = "$ldir/email.conf";
$conf = "/etc/ssmtp/ssmtp.conf";

if (-e $conf && $ARGV[0] ne "--force") {
	print "File

$conf

exists. Remove it first if you want to update
email config, or run this script with '--force':

   email-init --force

";
	exit;
};



if (!-e "$lconf") {
    system "mkdir -p '$ldir'";
    system "cp '$ENV{HOME}/bushcraft/config/email.conf' '$lconf'";
    print "Please edit the email configuration!";
    sleep 2;
    system "nano '$lconf'";
    system "chown pi '$lconf'";
} else {

};

if ($whoami ne "root") {
   print "Running as root!";
   system "sudo $0";
   exit;
};
# Need to fetch config file.
system "sudo apt-get update; 
sudo apt-get install ssmtp
sudo apt-get install mailutils";

open F,">$conf";
print F "
root=postmaster
mailhub=smtp.gmail.com:587
hostname=raspberrypi
UseSTARTTLS=YES
";
close F;
system "cat '$lconf' >> $conf";
