#!/usr/bin/perl
# See 
# http://iqjar.com/jar/sending-emails-from-the-raspberry-pi/
# for details.

$ldir = "$ENV{HOME}/.config/bushcraft/";

$lconf = "$ldir/email.cfg";
$lconf2 = "$ldir/ssmtp.conf";
$conf = "/etc/ssmtp/ssmtp.conf";

if (-e $conf && $ARGV[0] ne "--force") {
	print "File

$conf

exists. Remove it first if you want to update
email config, or run this script with '--force':

   email-init --force

";
	exit;
};

if ($ARGV[0] eq "-m") {
    print "Manual configuration\n";
    if (!-e "$lconf") {
	system "mkdir -p '$ldir'";
	system "cp '$ENV{HOME}/bushcraft/config/email.cfg' '$lconf'";
	print "Please edit the email configuration!";
	sleep 5;
	system "nano '$lconf'";
	system "chown pi '$lconf'";
    } else {
	
    };
};

print "Updating installation.....\n";

system "sudo apt-get update; 
sudo apt-get install ssmtp
sudo apt-get install mailutils";

print "Writing config files ....\n";
open F,">$lconf2";
print F "
root=postmaster
mailhub=smtp.gmail.com:587
hostname=raspberrypi
UseSTARTTLS=YES
";
close F;
system "cat '$lconf' >> '$lconf2'";

system "sudo cp '$lconf2' '$conf'";

if (-e $conf) {
    print "SUCCESS
$conf 
was installed.
";

} else {
    print "NOT SUCCESSFUL!!\n";

};
