#!/usr/bin/perl

if (!-e "/boot/bootcode.bin") {
    print "This programme is meant for running on Raspberry Pi\n";
   print "Exit.\n";
   exit;
};

if ($ARGV[0] eq "off" || $ARGV[0] eq "--off") {
   system "rm .config/autostart/firststart.desktop";
   system "killall firststart";
   print "Stopped all instances of $0. Will not run again.\n";
   exit;
};

chdir();
system "cd; mkdir .config; mkdir .config/autostart;" if !-d ".config/autostart";
open F,">.config/autostart/firststart.desktop";
print F "[Desktop Entry]
Type=Application
Name=firststart
Exec=firststart
StartupNotify=false
";
close F;

system("sudo mkdir /boot/config");
system("sudo touch /boot/config/speak_ifconfig.cfg");
