#!/bin/sh
# We should check that the packages managed to install...
sudo apt-get update
sudo apt-get -y install openssh-server tightvncserver openvpn tmux curl wget ytalk screen minicom emacs apt-zip apt-offline vncviewer festival acct procinfo scrot

