#!/bin/perl

print "This programme is meant for running on Raspberry Pi";
if (!-e "/boot/bootcode.bin") {
   print "Exit.\n";
   exit;
};
chdir();
system "cd; mkdir .config; mkdir .config/autostart;" if !-d ".config/autostart";
open F,">.config/autostart/tightvnc.desktop";
print F "[Desktop Entry]
Type=Application
Name=TightVNC
Exec=vncserver :1
StartupNotify=false
";
close F;
