#!/usr/bin/perl

if (!-e "/boot/bootcode.bin") {
    print "This programme is meant for running on Raspberry Pi";
   print "Exit.\n";
   exit;
};
chdir();
system "cd; mkdir -p .config; mkdir -p .config/autostart;" if !-d ".config/autostart";
open F,">.config/autostart/sysinfo.desktop";
print F "[Desktop Entry]
Type=Application
Name=sysinfo
Exec=sudo bushcraft/bin_pi/sysinfo
StartupNotify=false
";
close F;

system "ls -la .config/autostart/sysinfo.desktop";
