#!/usr/bin/perl

if (-e "/boot/bootcode.bin") {
   chdir();
   chdir("bushcraft");
   system "
initreq
email-init
write-sysinfo-init-autostart
first-start-init-autostart
vnc-init-autostart
vnc-init-password
";
} else {
    print "
This script is meant for running on Raspberry Pi only.
Exiting.
";
};


