#!/usr/bin/perl
# This file is retrieved from tiny.cc/bush, to start the process.
if (!-e "bushcraft") {
  print "Trying to install bushcraft using git / wget / curl ...\n";
  system "git clone https://github.com/bjohas/bushcraft.git";
  if (!-e "bushcraft") {
    system "wget https://github.com/bjohas/bushcraft/archive/master.zip; unzip master.zip";
  };  
  if (!-e "bushcraft") {
    system "curl https://github.com/bjohas/bushcraft/archive/master.zip; unzip master.zip";
  };
  if (!-e "bushcraft") {
    print "bushcraft failed to install... Try to get this file https://github.com/bjohas/bushcraft/archive/master.zip in a different way...";
  } else {
    print "bushcraft installation finished.\n";
    print "If you are on Raspberry Pi, now type

    sh bushcraft/bushcraft-init-pi

or if you are on another linux computer, type

    sh bushcraft/bushcraft-init

to initialise and install further required programs.
You can also delete this file now:

    rm bush

";
  };
} else {
  system "cd bushcraft; git pull";
};
