#!/usr/bin/perl

if (-e "/boot/bootcode.bin") {
   chdir();
   chdir("bushcraft");
   system "
initreq
write-sysinfo-init-autostart
first-start-init-autostart
cron-init
vnc-init-autostart
vnc-init-password
";
print "
If you want email to work, please enter gmail user / password
in 
      config/email.conf
and then run
      email-init
";

} else {
    print "
This script is meant for running on Raspberry Pi only.
Exiting.
";
};


