#!/usr/bin/perl
# Needs writing: Script that reads system setting from /boot/config/ such as
# hostname, wifi login, whether to shutdown after start
# and sets them.

# needs to be run as sudo
($whoami = `whoami`) =~ s/\n//;
if ($whoami ne "root") {
   print "Running as root!";
   system "sudo $0";
   exit;
};
$cfg = "/boot/config";
if (-e "/boot/bootcode.bin") {
    if (!-e $cfg) {
	mkdir($cfg);
    } else {
        if (-e "$cfg/hostname") {
    	    system("cp","$cfg/hostname","/etc/hostname");
	};	    
    };
} else {
	print "
This script is meant for running on Raspberry Pi only.
Exiting.
";
};
