#!/usr/bin/perl

# http://elinux.org/RPI_vcgencmd_usage
# https://major.io/icanhazip-com-faq/
if (-e "/boot") {
    if (!-e "/boot/logs") {
	mkdir("/boot/logs");
    };
    $logs = "/boot/logs";
    system "cat /proc/cpuinfo > $logs/cpuinfo.txt";
    system "ifconfig > $logs/ifconfig.txt";
    system "wget -q -O $logs/external_ip.txt http://icanhazip.com/";
    system "cat /etc/hostname > $logs/hostname.txt";
    system "vcgencmd version > $logs/vcgencmd.version.txt";
    system "vcgencmd measure_temp > $logs/vcgencmd.measure_temp.txt";
    system "vcgencmd measure_volts core > $logs/vcgencmd.measure_volts.core.txt";
};
