#!/usr/bin/perl

system "sudo modprobe w1-gpio; sudo modprobe w1-therm";
$out = `cat /sys/bus/w1/devices/28-*/w1_slave`;
$out =~ m/^(\w\w) (\w\w)/g;
$hex = $2.$1;
$t1 = hex($hex);
$out =~ m/t\=(\d+)/gs;
$t_direct = $1;
#printf "$t1 => d=%d x=%x o=%o b=%b\n",($t1) x 4;
$tb = sprintf "%b", $t1;
if ($tb =~ m/^\d+(\d)(\d{10})$/) {
    $sign = $1;
    $val = $2;
#    print "$sign, $val\n";
    if ($sign == 1) {
        $val =~ tr/01/10/;
        $t2 = bin2dec($val)+1;
    } else {
        $t2 = bin2dec($val);
    };
    $s2 = "+" if $sign == 0;
    $s2 = "-" if $sign == 1;
} else {
    $t2 = $t1;
};
$t2 = $t2 / 16;
print "T=$s2$t2
T_hexadecimal=$hex
t=$t_direct
";

if ($ARGV[0] eq "-l") {
    mkdir("/home/pi/Desktop/temperature_log") if !-d "/home/pi/Desktop/temperature_log";
    open F,">>/home/pi/Desktop/temperature_log/temperature.log";
    print F "$s2$t2\n";
    close F;

    open F,"</home/pi/Desktop/temperature_log/temperature.log";
    while (<F>) {
	s/\n//;
	push @a, $_;
    };
    close F;

    $vals = join ", ",@a;

    open F,">/home/pi/Desktop/temperature_log/data.js";
    print F "
function get_data() {
    var val = [$vals];
    return val;
};
";
    close F;
};

sub bin2dec {
        unpack("N", pack("B32", substr("0" x 32 . shift, -32)));
}
