#!/bin/perl

print "This programme is meant for running on Raspberry Pi";
if (!-e "/boot/bootcode.bin") {
   print "Exit.\n";
   exit;
};
chdir();
system "cd; mkdir .config; mkdir .config/autostart;" if !-d ".config/autorstart";
open F,">.config/autostart/sysinfo.desktop";
print F "[Desktop Entry]
Type=Application
Name=sysinfo
Exec=sudo bushcraft/sysinfo
StartupNotify=false
";
close F;
