#!/usr/bin/perl

$logs = "/boot/logs";
system "sudo mkdir $logs" if !-e $logs;
$ip = `cat $logs/external_ip.txt`;
if ($ip eq "" || $ARGV[0] eq "--update") {
    if (!-e $logs) {
	mkdir($logs);
    };	
    system "sudo wget -q -O $logs/external_ip.txt http://icanhazip.com/";
    $ip = `cat $logs/external_ip.txt`;
};
$ip =~ s/\n//s;
print $ip;
