#!/usr/bin/perl

$conf = "$ENV{HOME}/.config/bushcraft/";
if (-e "$conf/feedback.cfg") {
    open F,"$conf/feedback.cfg";
    while (<F>) {
	if (m/^email\=(.*)$/) {
	    $email = $1;
	};
	if (m/^enabled\=\s*(\d)\s*$/) {
	    $enabled = $1;
	};
    };
    close F;
    $serial = `$ENV{HOME}/bushcraft/bin_pi/serialnumber`;
    $ip = `ipaddress`;
# @ARGV here is present to allow extra arguments to scrot
    system "scrot @ARGV -e 'sendfile $f'";
    print "Screenshot...\n";
} else {
    if ($ARGV[0] eq "--onlyifconfigured") {
    } else {
	print "
Sorry, but 
   $conf
is not set up.
";
    };
};
