#!/usr/bin/perl

$conf = "$ENV{HOME}/.config/bushcraft/";
if (-e "$conf/feedback.cfg") {
    open F,"$conf/feedback.cfg";
    while (<F>) {
	if (m/^email\=(.*)$/) {
	    $email = $1;
	};
    };
    close F;
    $serial = `serialnumber`;
    $logs = "/boot/logs";
    $ip = `cat $logs/external_ip.txt`;
    if ($ip eq "") {
	if (!-e $logs) {
	    mkdir($logs);
	};	
	system "wget -q -O $logs/external_ip.txt http://icanhazip.com/";
	$ip = `cat $logs/external_ip.txt`;
    };
    $ip =~ s/\n//s;
    $str = "$logs/serial.txt";
#    open F,"|sudo mutt -s \"Feedback from $serial, with $ip\" -a $str -- $email";
    open F,"|sudo mutt -s \"Feedback from $serial, with $ip\" -a $str -- $email";
    print F "See attached files.\n";
    close F;
} else {
    if ($ARGV[0] eq "--onlyifconfigured") {
    } else {
	print "
Sorry, but 
   $conf
is not set up.
";
    };
};
