#!/usr/bin/perl

$conf = "$ENV{HOME}/.config/bushcraft/";
if (-e "$conf/feedback.cfg") {
    open F,"$conf/feedback.cfg";
    while (<F>) {
	if (m/^email\=(.*)$/) {
	    $email = $1;
	};
	if (m/^enabled\=\s*(\d)\s*$/) {
	    $enabled = $1;
	};
    };
    close F;
    $serial = `$ENV{HOME}/bushcraft/bin_pi/serialnumber`;
    $ip = `ipaddress`;
    @a = @ARGV;
    foreach (@a) {
	s/\'/\\\'/g;
	s/\"/\\\"/g;
	$_ = "\"" . $_ . "\"";
    };
    $str = join " ",@a;
    open F,"|sudo mutt -s \"File from $serial, with $ip\" -a $str -- $email";
    print F "See attached files.\n";
    print F "Date: ",`date`;
    close F;
    print "File from $serial, with $ip and logfile $str sent to $email\n";
} else {
    if ($ARGV[0] eq "--onlyifconfigured") {
    } else {
	print "
Sorry, but 
   $conf
is not set up.
";
    };
};
