#!/usr/bin/perl

$conf = "$ENV{HOME}/.config/bushcraft/";
if (-e "$conf/feedback.cfg") {
    open F,"$conf/feedback.cfg";
    while (<F>) {
	if (m/^email\=(.*)$/) {
	    $email = $1;
	};
	if (m/^enabled\=\s*(\d)\s*$/) {
	    $enabled = $1;
	};
    };
    close F;
    if ($ARGV[0] ne "--onlyifconfigured" || $enabled eq "1") {
	$serial = `$ENV{HOME}/bushcraft/bin_pi/serialnumber`;
	$logs = "/boot/logs";
	$ip = `cat $logs/external_ip.txt`;
	if ($ip eq "") {
	    if (!-e $logs) {
		mkdir($logs);
	    };	
	    system "wget -q -O $logs/external_ip.txt http://icanhazip.com/";
	    $ip = `cat $logs/external_ip.txt`;
	};
	$ip =~ s/\n//s;
	$str = "$logs/serial.txt";
#	$str = "$logs/logs.tgz";
	$str = "$logs/sysinfo_logs.tgz";
	open F,"|sudo mutt -s \"Feedback from $serial, with $ip\" -a $str -- $email";
	print F "See attached files.\n";
	print F "Date: ",`date`;
	close F;
    } else {
	if ($ARGV[0] eq "--onlyifconfigured") {
	} else {
	    print "Sorry, $conf has enabled=0\n";
	};
    };
} else {
    if ($ARGV[0] eq "--onlyifconfigured") {
    } else {
	print "
Sorry, but 
   $conf
is not set up.
";
    };
};
