#!/usr/bin/perl

$conf = "$ENV{HOME}/.config/bushcraft/";
if (-e "$conf/feedback.cfg") {
    open F,"$conf/feedback.cfg";
    while (<F>) {
	if (m/^email\=(.*)$/) {
	    $email = $1;
	};
	if (m/^enabled\=\s*(\d)\s*$/) {
	    $enabled = $1;
	};
    };
    close F;
    $serial = `$ENV{HOME}/bushcraft/bin_pi/serialnumber`;
    $ip = `ipaddress`;
    open F,"|sudo mutt -s \"Text from $serial, with $ip\" -- $email";
    print F "Text follows...\n";
    print F "Date: ",`date`;
    while (<>) {
	print F;
    };
    close F;
    print "Feedback from $serial, with $ip and logfile $str sent to $email\n";
} else {
    if ($ARGV[0] eq "--onlyifconfigured") {
    } else {
	print "
Sorry, but 
   $conf
is not set up.
";
    };
};
